# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sense',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
