# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Form Slug')),
                ('label', models.CharField(max_length=1000)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('parent_entry', models.ManyToManyField(related_name='_form_parent_entry_+', to='dictionary.Entry')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='forms',
            field=models.ManyToManyField(blank=True, related_name='_entry_forms_+', to='dictionary.Form'),
        ),
    ]
