# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='member_of',
            field=models.ManyToManyField(blank=True, related_name='_artist_member_of_+', to='dictionary.Artist'),
        ),
    ]
