# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_sense_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collocate',
            name='frequency',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='publish',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='example',
            name='features_entities',
            field=models.ManyToManyField(db_index=True, related_name='_example_features_entities_+', to='dictionary.NamedEntity'),
        ),
        migrations.AlterField(
            model_name='example',
            name='release_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='Place Slug'),
        ),
        migrations.AlterField(
            model_name='sense',
            name='examples',
            field=models.ManyToManyField(db_index=True, related_name='_sense_examples_+', to='dictionary.Example'),
        ),
        migrations.AlterField(
            model_name='sense',
            name='headword',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Headword'),
        ),
        migrations.AlterField(
            model_name='sense',
            name='publish',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='sense',
            name='xml_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='XML id'),
        ),
        migrations.AlterField(
            model_name='senserhyme',
            name='frequency',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xref',
            name='xref_type',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='xref',
            name='xref_word',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
    ]
