# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20151230_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Entity Slug'),
        ),
        migrations.AddField(
            model_name='synset',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Entity Slug'),
        ),
    ]
