# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-20 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20160525_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, null=True, verbose_name='Lyrics'),
        ),
    ]
