# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20160219_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='feat_artist',
            field=models.ManyToManyField(blank=True, null=True, related_name='_example_feat_artist_+', to='dictionary.Artist'),
        ),
        migrations.AlterField(
            model_name='example',
            name='features_entities',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='_example_features_entities_+', to='dictionary.NamedEntity'),
        ),
        migrations.AlterField(
            model_name='song',
            name='feat_artist',
            field=models.ManyToManyField(blank=True, null=True, related_name='_song_feat_artist_+', to='dictionary.Artist'),
        ),
    ]
