# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20171103_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Artist')),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Sense')),
            ],
            options={
                'ordering': ['score'],
            },
        ),
    ]
