# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20151230_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Domain Slug'),
        ),
        migrations.AlterField(
            model_name='synset',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='SynSet Slug'),
        ),
    ]
