# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20160221_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='image',
        ),
        migrations.AlterField(
            model_name='artist',
            name='featured_examples',
            field=models.ManyToManyField(blank=True, related_name='_artist_featured_examples_+', to='dictionary.Example'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='featured_senses',
            field=models.ManyToManyField(blank=True, related_name='_artist_featured_senses_+', to='dictionary.Sense'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='featured_songs',
            field=models.ManyToManyField(blank=True, related_name='_artist_featured_songs_+', to='dictionary.Song'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='primary_examples',
            field=models.ManyToManyField(blank=True, related_name='_artist_primary_examples_+', to='dictionary.Example'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='primary_senses',
            field=models.ManyToManyField(blank=True, related_name='_artist_primary_senses_+', to='dictionary.Sense'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='primary_songs',
            field=models.ManyToManyField(blank=True, related_name='_artist_primary_songs_+', to='dictionary.Song'),
        ),
        migrations.AlterField(
            model_name='example',
            name='feat_artist',
            field=models.ManyToManyField(blank=True, related_name='_example_feat_artist_+', to='dictionary.Artist'),
        ),
        migrations.AlterField(
            model_name='example',
            name='features_entities',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='_example_features_entities_+', to='dictionary.NamedEntity'),
        ),
        migrations.AlterField(
            model_name='sense',
            name='domains',
            field=models.ManyToManyField(blank=True, related_name='_sense_domains_+', to='dictionary.Domain'),
        ),
        migrations.AlterField(
            model_name='sense',
            name='features_entities',
            field=models.ManyToManyField(blank=True, related_name='_sense_features_entities_+', to='dictionary.NamedEntity'),
        ),
        migrations.AlterField(
            model_name='sense',
            name='synset',
            field=models.ManyToManyField(blank=True, related_name='_sense_synset_+', to='dictionary.SynSet'),
        ),
        migrations.AlterField(
            model_name='sense',
            name='xrefs',
            field=models.ManyToManyField(blank=True, related_name='_sense_xrefs_+', to='dictionary.Xref'),
        ),
        migrations.AlterField(
            model_name='song',
            name='feat_artist',
            field=models.ManyToManyField(blank=True, related_name='_song_feat_artist_+', to='dictionary.Artist'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
