# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20160209_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='contains',
            field=models.ManyToManyField(blank=True, related_name='_place_contains_+', to='dictionary.Place'),
        ),
        migrations.AddField(
            model_name='place',
            name='full_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='within',
            field=models.ManyToManyField(blank=True, related_name='_place_within_+', to='dictionary.Place'),
        ),
    ]
