# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20151230_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='artist_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Artist Slug'),
        ),
    ]
