# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20160221_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticClass',
            fields=[
                ('name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
                ('broader', models.ManyToManyField(blank=True, to='dictionary.SemanticClass')),
                ('senses', models.ManyToManyField(blank=True, related_name='_semanticclass_senses_+', to='dictionary.Sense')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Semantic Classes',
            },
        ),
        migrations.AddField(
            model_name='domain',
            name='broader',
            field=models.ManyToManyField(blank=True, to='dictionary.Domain'),
        ),
        migrations.AddField(
            model_name='sense',
            name='semantic_classes',
            field=models.ManyToManyField(blank=True, related_name='_sense_semantic_classes_+', to='dictionary.SemanticClass'),
        ),
    ]
