# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20151210_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sense',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Usage Note'),
        ),
    ]
