# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_example_artist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='featured_senses',
            field=models.ManyToManyField(related_name='_artist_featured_senses_+', to='dictionary.Sense'),
        ),
        migrations.AddField(
            model_name='artist',
            name='primary_senses',
            field=models.ManyToManyField(related_name='_artist_primary_senses_+', to='dictionary.Sense'),
        ),
    ]
