# Generated by Django 2.2.4 on 2020-02-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='spot_uri',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Spot URI'),
        ),
    ]
