# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20160214_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='within',
        ),
        migrations.AddField(
            model_name='place',
            name='comment',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='contains',
            field=models.ManyToManyField(blank=True, to='dictionary.Place'),
        ),
    ]
