# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20160214_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True, verbose_name='Domain Slug'),
        ),
        migrations.AlterField(
            model_name='namedentity',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True, verbose_name='Entity Slug'),
        ),
    ]
