# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20160103_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
