# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 17:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20151211_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headword', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('publish', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='sense',
            name='lemma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canonical_form_of', to='dictionary.Word'),
        ),
        migrations.AddField(
            model_name='sense',
            name='xml_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lecagy XML id'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
    ]
