# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_entry_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='sense',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Sense Slug'),
        ),
    ]
