# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 17:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_auto_20151213_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 13, 17, 52, 22, 174324, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
