# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_auto_20160215_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyriclink',
            name='target_slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
