# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_auto_20151217_1714'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='SynSet',
        ),
        migrations.RemoveField(
            model_name='word',
            name='image',
        ),
        migrations.RemoveField(
            model_name='word',
            name='rhymes_with',
        ),
        migrations.RemoveField(
            model_name='word',
            name='senses',
        ),
        migrations.AddField(
            model_name='sense',
            name='parent_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_sense', to='dictionary.Entry'),
        ),
        migrations.AlterField(
            model_name='sense',
            name='headword',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Headword'),
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
