# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_auto_20151217_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='senses',
            field=models.ManyToManyField(blank=True, null=True, related_name='_entry_senses_+', to='dictionary.Sense'),
        ),
        migrations.RemoveField(
            model_name='sense',
            name='parent_entry',
        ),
        migrations.AddField(
            model_name='sense',
            name='parent_entry',
            field=models.ManyToManyField(related_name='_sense_parent_entry_+', to='dictionary.Entry'),
        ),
    ]
