# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_auto_20151217_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='senses',
            field=models.ManyToManyField(blank=True, related_name='_entry_senses_+', to='dictionary.Sense'),
        ),
    ]
