# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_auto_20160106_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collocate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('collocate_lemma', models.CharField(blank=True, max_length=1000, null=True)),
                ('target_slug', models.SlugField(blank=True, null=True)),
                ('target_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('parent_sense', models.ManyToManyField(related_name='_collocate_parent_sense_+', to='dictionary.Sense')),
            ],
            options={
                'ordering': ['collocate_lemma'],
            },
        ),
        migrations.CreateModel(
            name='Rhyme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rhyme_word', models.CharField(blank=True, max_length=1000, null=True)),
                ('target_slug', models.SlugField(blank=True, null=True)),
                ('target_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('parent_sense', models.ManyToManyField(related_name='_rhyme_parent_sense_+', to='dictionary.Sense')),
            ],
            options={
                'ordering': ['rhyme_word'],
            },
        ),
        migrations.AlterField(
            model_name='xref',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sense',
            name='collocates',
            field=models.ManyToManyField(related_name='_sense_collocates_+', to='dictionary.Collocate'),
        ),
        migrations.AddField(
            model_name='sense',
            name='rhymes',
            field=models.ManyToManyField(related_name='_sense_rhymes_+', to='dictionary.Rhyme'),
        ),
    ]
