# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 17:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_auto_20151217_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='example',
            name='lyric_html',
        ),
        migrations.RemoveField(
            model_name='example',
            name='lyric_tokens',
        ),
        migrations.RemoveField(
            model_name='example',
            name='song_id',
        ),
        migrations.AddField(
            model_name='artist',
            name='featured_examples',
            field=models.ManyToManyField(related_name='_artist_featured_examples_+', to='dictionary.Example'),
        ),
        migrations.AddField(
            model_name='artist',
            name='primary_examples',
            field=models.ManyToManyField(related_name='_artist_primary_examples_+', to='dictionary.Example'),
        ),
        migrations.AddField(
            model_name='example',
            name='illustrates_senses',
            field=models.ManyToManyField(related_name='_example_illustrates_senses_+', to='dictionary.Sense'),
        ),
        migrations.AddField(
            model_name='example',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sense',
            name='examples',
            field=models.ManyToManyField(related_name='_sense_examples_+', to='dictionary.Example'),
        ),
        migrations.RemoveField(
            model_name='example',
            name='artist',
        ),
        migrations.AddField(
            model_name='example',
            name='artist',
            field=models.ManyToManyField(related_name='_example_artist_+', to='dictionary.Artist'),
        ),
        migrations.RemoveField(
            model_name='example',
            name='feat_artist',
        ),
        migrations.AddField(
            model_name='example',
            name='feat_artist',
            field=models.ManyToManyField(related_name='_example_feat_artist_+', to='dictionary.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='examples',
            field=models.ManyToManyField(related_name='_song_examples_+', to='dictionary.Example'),
        ),
        migrations.AddField(
            model_name='example',
            name='song',
            field=models.ManyToManyField(related_name='_example_song_+', to='dictionary.Song'),
        ),
    ]
