# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_auto_20160106_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='collocate',
            name='source_sense_xml_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Source XML ID'),
        ),
        migrations.AddField(
            model_name='rhyme',
            name='source_sense_xml_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Source XML ID'),
        ),
        migrations.AlterField(
            model_name='sense',
            name='xml_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='XML id'),
        ),
    ]
