# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0015_auto_20160106_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedentity',
            name='mentioned_at_senses',
            field=models.ManyToManyField(blank=True, related_name='_namedentity_mentioned_at_senses_+', to='dictionary.Sense'),
        ),
        migrations.AddField(
            model_name='sense',
            name='features_entities',
            field=models.ManyToManyField(related_name='_sense_features_entities_+', to='dictionary.NamedEntity'),
        ),
    ]
