# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 18:48
from __future__ import unicode_literals

from django.db import migrations
import django_date_extensions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0015_auto_20151218_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='release_date',
            field=django_date_extensions.fields.ApproximateDateField(max_length=10, verbose_name='Release Date'),
        ),
    ]
