# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0016_auto_20151218_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='release_date_string',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Release Date String'),
        ),
        migrations.AlterField(
            model_name='example',
            name='release_date',
            field=models.DateField(verbose_name='Release Date'),
        ),
    ]
