# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0017_auto_20151219_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='artist_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Artist Name'),
        ),
        migrations.AlterField(
            model_name='example',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Release Date'),
        ),
    ]
