# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0017_namedentity_pref_label_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='LyricLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('link_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('target_slug', models.SlugField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('parent_example', models.ManyToManyField(related_name='_lyriclink_parent_example_+', to='dictionary.Example')),
            ],
            options={
                'ordering': ['link_text'],
            },
        ),
        migrations.AddField(
            model_name='example',
            name='lyric_links',
            field=models.ManyToManyField(related_name='_example_lyric_links_+', to='dictionary.LyricLink'),
        ),
    ]
