# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0018_auto_20151220_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('senses', models.ManyToManyField(blank=True, related_name='_domain_senses_+', to='dictionary.Sense')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('examples', models.ManyToManyField(blank=True, related_name='_entity_examples_+', to='dictionary.Example')),
            ],
        ),
        migrations.CreateModel(
            name='SynSet',
            fields=[
                ('name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('senses', models.ManyToManyField(blank=True, related_name='_synset_senses_+', to='dictionary.Sense')),
            ],
        ),
        migrations.AddField(
            model_name='example',
            name='features_entities',
            field=models.ManyToManyField(related_name='_example_features_entities_+', to='dictionary.Entity'),
        ),
        migrations.AddField(
            model_name='sense',
            name='domains',
            field=models.ManyToManyField(related_name='_sense_domains_+', to='dictionary.Domain'),
        ),
        migrations.AddField(
            model_name='sense',
            name='synset',
            field=models.ManyToManyField(related_name='_sense_synset_+', to='dictionary.SynSet'),
        ),
    ]
