# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0018_auto_20160107_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyriclink',
            name='target_lemma',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
