# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0019_auto_20151220_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='examples',
            field=models.ManyToManyField(blank=True, related_name='_song_examples_+', to='dictionary.Example'),
        ),
    ]
