# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0019_lyriclink_target_lemma'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='last_updated',
            field=models.DateField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
    ]
