# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0020_auto_20151221_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='examples',
        ),
        migrations.RemoveField(
            model_name='example',
            name='song',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
