# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0020_entry_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='sense',
            name='cites_artists',
            field=models.ManyToManyField(related_name='_sense_cites_artists_+', to='dictionary.Artist'),
        ),
    ]
