# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0021_sense_cites_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='origin_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Origin'),
        ),
        migrations.RemoveField(
            model_name='artist',
            name='origin',
        ),
        migrations.AddField(
            model_name='place',
            name='artists',
            field=models.ManyToManyField(related_name='_place_artists_+', to='dictionary.Artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='origin',
            field=models.ManyToManyField(related_name='_artist_origin_+', to='dictionary.Place'),
        ),
    ]
