# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0021_auto_20151221_0707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='editor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name'], 'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['headword'], 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='example',
            options={'ordering': ['release_date', 'artist_name']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='sense',
            options={'ordering': ['xml_id']},
        ),
        migrations.AlterModelOptions(
            name='synset',
            options={'ordering': ['name'], 'verbose_name_plural': 'SynSets'},
        ),
    ]
