# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0022_auto_20151222_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
    ]
