# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0022_auto_20160113_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='origin_name',
        ),
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Sense Slug'),
        ),
    ]
