# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0023_auto_20160113_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sense Slug'),
        ),
    ]
