# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0024_auto_20160113_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Place Slug'),
        ),
    ]
