# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0024_auto_20151222_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
