# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0025_entity_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
