# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0026_auto_20151222_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='examples',
        ),
        migrations.RemoveField(
            model_name='example',
            name='features_entities',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
