# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0028_auto_20151222_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('pref_label', models.CharField(blank=True, max_length=1000, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Named Entities',
            },
        ),
        migrations.RemoveField(
            model_name='entity',
            name='examples',
        ),
        migrations.AlterField(
            model_name='example',
            name='features_entities',
            field=models.ManyToManyField(related_name='_example_features_entities_+', to='dictionary.NamedEntity'),
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.AddField(
            model_name='namedentity',
            name='examples',
            field=models.ManyToManyField(blank=True, related_name='_namedentity_examples_+', to='dictionary.Example'),
        ),
    ]
