name: CI
on: push

jobs:
  deploy:
    name: "Deploy to prod"
    runs-on: ubuntu-latest
    env:
      VENV: '/home/${{ secrets.USERNAME }}/.virtualenvs/the_right_rhymes/bin'
      SOURCE: '/home/${{ secrets.USERNAME }}/the_right_rhymes'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_KEY: ${{ secrets.KEY }}
          SSH_HOST: ${{ secrets.HOST }}

      - name: Check out the source
        run: ssh prod 'cd ${{ env.SOURCE }} && git pull'

      - name: Update source for prod
        run: ssh prod 'cd ${{ env.SOURCE }} && sed "s/DEBUG = True/DEBUG = False/g" the_right_rhymes/settings.py > the_right_rhymes/settings.py.tmp && mv the_right_rhymes/settings.py.tmp the_right_rhymes/settings.py'

      - name: Upgrade virtualenv
        run: ssh prod '${{ env.VENV }}/pip install --upgrade pip && ${{ env.VENV }}/pip install -r ${{ env.SOURCE }}/requirements.txt'

      - name: Update static files
        run: ssh prod 'cd ${{ env.SOURCE }} && ${{ env.VENV }}/python manage.py collectstatic --noinput'

      - name: Update database
        run: ssh prod 'cd ${{ env.SOURCE }} && ${{ env.VENV }}/python manage.py migrate --noinput'

      - name: Start the server
        run: ssh prod 'sudo systemctl restart gunicorn'
